CREATE TABLE `movimiento_stock` (
  
  `idMOVIMIENTO_STOCK` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUCTO` VARCHAR(50) NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(50) NOT NULL,
  `CANTIDAD` DOUBLE NOT NULL,
  `CLIENTE_PROVEEDOR` VARCHAR(50) NOT NULL,
  `TIPO_MOVIMIENTO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMOVIMIENTO_STOCK`)
  
)




CREATE TABLE `producto` (
  `idPRODUCTO` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `MARCA` VARCHAR(45) NULL DEFAULT NULL,
  `UNIDAD_MEDIDA` VARCHAR(50) NOT NULL,
  `ALMACEN` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPRODUCTO`)
)

CREATE TABLE `cliente` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(45) NULL DEFAULT NULL,
  `APELLIDO_PATERNO` VARCHAR(45) NULL DEFAULT NULL,
  `APELLIDO_MATERNO` VARCHAR(45) NULL DEFAULT NULL,
  `DIRECCION` VARCHAR(45) NULL DEFAULT NULL,
  `TELEFONO` INT NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `TIPO_DOCUMENTO` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idCLIENTE`)
 )

 CREATE TABLE `proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(45) NULL DEFAULT NULL,
  `APELLIDO_PATERNO` VARCHAR(45) NULL DEFAULT NULL,
  `APELLIDO_MATERNO` VARCHAR(45) NULL DEFAULT NULL,
  `DIRECCION` VARCHAR(45) NULL DEFAULT NULL,
  `TELEFONO` INT NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `TIPO_DOCUMENTO` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedor`)
 )